#include "core/Commands.h"

#include <fstream>

namespace wid::core {

namespace {
std::vector<ScriptedCommand>& pick(CommandSet&, CommandPhase, std::vector<ScriptedCommand>& pre, std::vector<ScriptedCommand>& post, CommandPhase p) {
    return p == CommandPhase::PreLogon ? pre : post;
}
} // namespace

void CommandSet::add(CommandPhase phase, ScriptedCommand cmd) {
    (phase == CommandPhase::PreLogon ? pre_ : post_).push_back(std::move(cmd));
}

void CommandSet::clear(CommandPhase phase) {
    (phase == CommandPhase::PreLogon ? pre_ : post_).clear();
}

void CommandSet::remove(CommandPhase phase, std::size_t index) {
    auto& v = (phase == CommandPhase::PreLogon ? pre_ : post_);
    if (index < v.size()) v.erase(v.begin() + index);
}

bool CommandSet::moveUp(CommandPhase phase, std::size_t i) {
    auto& v = (phase == CommandPhase::PreLogon ? pre_ : post_);
    if (i == 0 || i >= v.size()) return false;
    std::swap(v[i], v[i - 1]);
    return true;
}

bool CommandSet::moveDown(CommandPhase phase, std::size_t i) {
    auto& v = (phase == CommandPhase::PreLogon ? pre_ : post_);
    if (i + 1 >= v.size()) return false;
    std::swap(v[i], v[i + 1]);
    return true;
}

const std::vector<ScriptedCommand>& CommandSet::list(CommandPhase phase) const {
    return phase == CommandPhase::PreLogon ? pre_ : post_;
}

bool CommandSet::writeSetupComplete(const fs::path& mountDir,
                                    const std::vector<std::wstring>& extraPreLogonLines) const {
    fs::path scriptsDir = mountDir / L"Windows" / L"Setup" / L"Scripts";
    std::error_code ec;
    fs::create_directories(scriptsDir, ec);
    fs::path file = scriptsDir / L"SetupComplete.cmd";

    std::wofstream f(file);
    if (!f) return false;
    // Visible-cmd wrapper: Windows invokes SetupComplete.cmd hidden by
    // default. We re-spawn ourselves via 'start cmd' the first time we
    // run, so the user sees the configuration scroll past during the
    // final "Getting ready" screen.
    f << L"@echo off\r\n";
    f << L"rem Generated by WID Utility. Runs in SYSTEM context before first logon.\r\n";
    f << L"title WID Utility - finalizing\r\n";
    f << L"if \"%WID_VISIBLE%\"==\"\" (\r\n";
    f << L"  set WID_VISIBLE=1\r\n";
    f << L"  start \"WID Utility\" /wait cmd /c \"%~f0\"\r\n";
    f << L"  exit /b\r\n";
    f << L")\r\n";
    f << L"echo.\r\n";
    f << L"echo === WID Utility: applying tweaks and installing apps ===\r\n";
    f << L"echo.\r\n";

    for (const auto& line : extraPreLogonLines) {
        f << L"echo ^> " << line << L"\r\n";
        f << line << L"\r\n";
    }
    for (const auto& c : pre_) {
        if (!c.description.empty())
            f << L"rem " << c.description << L"\r\n";
        f << L"echo ^> " << c.commandLine << L"\r\n";
        if (c.continueOnError) {
            f << c.commandLine << L"\r\n";
        } else {
            f << c.commandLine << L" || exit /b 1\r\n";
        }
    }

    f << L"echo.\r\n";
    f << L"echo Done. Closing in 5 seconds.\r\n";
    f << L"timeout /t 5 /nobreak >nul\r\n";
    f << L"exit /b 0\r\n";
    return f.good();
}

} // namespace wid::core
